# Generated by Django 5.0.7 on 2024-09-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usermodel_age_usermodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='age',
        ),
    ]
