# Generated by Django 5.1.2 on 2024-10-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_usermodel_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='static\\Files')),
                ('uploaderemail', models.EmailField(max_length=254)),
                ('file_name', models.CharField(max_length=255)),
                ('encrypted_data', models.TextField()),
                ('keyword', models.CharField(max_length=255)),
                ('privatekey', models.BinaryField()),
                ('Publickey', models.BinaryField()),
                ('status', models.CharField(default='Encrypted', max_length=255)),
            ],
            options={
                'db_table': 'UploadFileModel',
            },
        ),
    ]
