# Generated by Django 5.1.2 on 2024-10-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_uploadfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='hash',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='Publickey',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='privatekey',
            field=models.TextField(),
        ),
    ]
