# Generated by Django 5.1.2 on 2024-10-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uploadfilemodel_hash_alter_uploadfilemodel_publickey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='auditstatus',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
