# Generated by Django 5.1.2 on 2024-10-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_uploadfilemodel_auditstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='static\\Files')),
                ('uploaderemail', models.EmailField(max_length=254)),
                ('file_name', models.CharField(max_length=255)),
                ('encrypted_data', models.TextField()),
                ('keyword', models.CharField(max_length=255)),
                ('privatekey', models.TextField()),
                ('Publickey', models.TextField()),
                ('hash', models.TextField(null=True)),
                ('status', models.CharField(default='Encrypted', max_length=255)),
                ('Requesteremail', models.CharField(max_length=100)),
                ('Rname', models.CharField(max_length=100)),
                ('key', models.IntegerField()),
            ],
            options={
                'db_table': 'RequestFileModel',
            },
        ),
    ]
