# Generated by Django 5.1.2 on 2024-10-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_requestfilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfilemodel',
            name='file',
            field=models.FileField(upload_to='static\\DECFiles'),
        ),
    ]
