# Generated by Django 5.1.2 on 2024-10-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_requestfilemodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfilemodel',
            name='fid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='requestfilemodel',
            name='key',
            field=models.IntegerField(null=True),
        ),
    ]
