# Generated by Django 5.1.2 on 2024-10-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_requestfilemodel_fid_alter_requestfilemodel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='Publickey',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='encrypted_data',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='hash',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='privatekey',
            field=models.BinaryField(),
        ),
    ]
