# Generated by Django 5.1.2 on 2024-10-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_uploadfilemodel_publickey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfilemodel',
            name='Publickey',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='requestfilemodel',
            name='encrypted_data',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='requestfilemodel',
            name='hash',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='requestfilemodel',
            name='privatekey',
            field=models.BinaryField(),
        ),
    ]
