# Generated by Django 5.1.2 on 2024-10-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_requestfilemodel_publickey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfilemodel',
            name='encrypted_data',
            field=models.TextField(),
        ),
    ]
